on:
  push:
    paths:
      - frontend/**
      - .github/workflows/**
  workflow_dispatch:


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: E2E tests
        run: |
          docker run \
            --entrypoint bash \
            -v "$PWD":/root \
            --workdir /root \
            yowgf/cypress-with-python:v0.0.1 \
            -c "$(cat ./.github/workflows/frontend-check-entrypoint.sh)"
